### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by cyrilfr** [smsapi/smsapi-java-client#27] opened 2024-11-12 16:47 UTC
I cannot send a message with SMSAPI Java lib 3.x.

This code:
```
   val action = smsApi.actionSend(number, text)
        .setSender(config.getString("api.sms.sender"))
        .setNormalize(true);

    return runAsync(() -> {
        try {
            val response = action.execute().list.stream().findFirst();

            if (response.isEmpty()) {
                throw new RuntimeException("No SMS API response available.");
            }

            if (response.get().isError()) {
                throw new RuntimeException(response.get().getError());
            }
        } catch (SmsapiException e) {
            throw new RuntimeException(e);
        }
    }, executionContext.current());
```

Throws an exception in my Java 17 app:

`java.lang.RuntimeException: pl.smsapi.exception.ProxyException: pom.xml (No such file or directory)`

**Comment by maciejlew** [comment] 2024-11-13 10:50
The exception you have may be misleading. See https://github.com/smsapi/smsapi-java-client/blob/90724437528093636f141946d3d2da33e1797526/src/main/java/pl/smsapi/api/action/AbstractAction.java#L73 line. The problem is `pom.xml (No such file or directory)`. It does not seem to be related to SMSAPI library.

Check out if you can send SMS as in example: https://github.com/smsapi/smsapi-java-client?tab=readme-ov-file#how-to-send-sms

ProxyException is marked as deprecated and would be removed in next release to mitigate such mistakes.

**Comment by cyrilfr** [comment] 2024-11-13 15:09
I forgot to mention that I was previously using v2.5 on https://labs.smsapi.com/maven/ and it worked fine. This happened when I updated to 3.x.

**Comment by maciejlew** [comment] 2024-11-18 13:19
That was a bug, indeed. Check out v3.0.1.

**Closed** 2024-11-20 08:49 UTC
Labels: bug
